name: Upload dotnet package
on:
  release:
    types: [created]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - run: dotnet build --configuration Release src/Core/Core.csproj
      - name: Create the package
        run: dotnet pack --configuration Release src/Core/Core.csproj
      - name: Publish the package to Nuget
        shell: bash
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push src/Core/bin/Release/*.nupkg --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json --skip-duplicate

